name: Android CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./Wine/gradlew
      
    - name: Upgrade Gradle Wrapper
      run: ./Wine/gradlew wrapper --gradle-version 7.5.1

    - name: Build with Gradle
      run: ./Wine/gradlew assembleDebug

    - name: Get Short SHA
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Wine-Android ${{ github.sha }}"
        tag_name: ${{ env.SHORT_SHA }}
        files: ./Wine/app/build/outputs/apk/debug/app-debug.apk
